## Project Agreement

Start Date: June 30, 2022

End Date: June 30, 2024

In collaboration with state fiscal health leadership, Provider shall identify key emerging challenges that will affect state budgets in the next five to 10 years and write a white paper for Pew.

a\. Prior to conducting the research, participate in a meeting (Methods Review Meeting), either via teleconference or in-person as designated by Pew, to discuss the proposed research design and methodology (Research Design).

b\. Research and analyze an emerging challenge, or challenges, that will affect state budgets in the medium to long-term and propose solutions to manage and mitigate these challenges.

c\. Provide Pew with a draft white paper in electronic format two (2) months prior to End Date \[i.e., April 30, 2024\], along with copies of all cited and referenced source documents, and annotated datasets and statistical code, with instructions that explain the analytic steps and code, so that Pew may conduct its own quality control review.

d\. Within three (3) months of Start Date \[i.e., Sept 30, 2022\], Provider will suggest to Pew the names and professional profiles of at least two (2) external peer reviewers. External peer reviewers shall not be personnel of Provider and shall be agreed upon by the Parties in advance. Provider will incorporate feedback from external peer reviewers, provided to Provider by Pew, into the white paper, and provide Pew with a document containing the rationale for any feedback that was not incorporated into the revised white paper.

e\. Provide Pew with the final white paper in electronic format on or before the End Date. The final white paper shall incorporate any feedback Pew provided on the draft white paper.
